name: Run pytest using conda in Ubuntu

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      fail-fast: false

    steps:
    - name: Cache conda
      uses: actions/cache@v2
      env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
      with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('environment.yml') }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.10.0
        auto-activate-base: false        
        miniforge-version: latest
        activate-environment: aoc2021
        channel-priority: strict
        #environment-file: environment.yml
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
    - uses: actions/checkout@v2
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
